# Generated by Django 4.1.5 on 2023-01-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, choices=[('corporate headoffice', 'Corporate Headoffice'), ('operation department', 'Operation Department'), ('work station', 'Work Station'), ('markinting devision', 'Markinting Devision')], max_length=255, null=True)),
                ('department', models.TextField()),
                ('date_time', models.DateTimeField(null=True)),
                ('incident_location', models.TextField()),
                ('severity', models.CharField(blank=True, max_length=255, null=True)),
                ('cause', models.TextField()),
                ('action', models.TextField()),
                ('types', models.CharField(blank=True, max_length=255, null=True)),
                ('nodes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-types'],
            },
        ),
    ]
