# Generated by Django 4.1.5 on 2023-01-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='date_time',
        ),
        migrations.AddField(
            model_name='incident',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
