# Generated by Django 4.1.5 on 2023-01-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDashboard', '0002_remove_incident_date_time_incident_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={},
        ),
    ]
