# Generated by Django 4.1.5 on 2023-01-05 18:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UserDashboard', '0003_alter_incident_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='nodes',
        ),
        migrations.AddField(
            model_name='incident',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(blank=True, choices=[('mild', 'mild'), ('moderate', 'moderate'), ('servese', 'servese'), ('fatal', 'fatal')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], max_length=3, null=True),
        ),
    ]
