# Generated by Django 4.1.5 on 2023-01-05 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserDashboard', '0004_remove_incident_created_by_remove_incident_nodes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
