# Generated by Django 4.1.5 on 2023-01-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDashboard', '0005_incident_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='user',
            new_name='report_by',
        ),
    ]
