# Generated by Django 4.1.5 on 2023-01-05 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserDashboard', '0006_rename_user_incident_report_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='report_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
