# Generated by Django 4.1.5 on 2023-01-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDashboard', '0007_alter_incident_report_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='report_by',
            new_name='user',
        ),
    ]
